package com.example.translator.model

import android.os.Parcelable
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.firebase.ml.naturallanguage.translate.FirebaseTranslateLanguage
import kotlinx.android.parcel.Parcelize

@Parcelize
@Entity(tableName = "languageTable")
data class Language(
    @PrimaryKey
    @ColumnInfo(name = "languageId")
    val languageId: Int,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "code")
    val code: String,

    @ColumnInfo(name = "selectedAsFromLanguage")
    var selectedAsFromLanguage: Boolean = false,

    @ColumnInfo(name = "selectedAsToLanguage")
    var selectedAsToLanguage: Boolean = false

) : Parcelable {
    companion object {
        fun getSupportedLanguages(): List<Language> {
            return listOf(
                Language(
                    FirebaseTranslateLanguage.NL,
                    "Dutch",
                    "nl",
                    true
                ),
                Language(
                    FirebaseTranslateLanguage.EN,
                    "English",
                    "en",
                    selectedAsToLanguage = true
                ),
                Language(
                    FirebaseTranslateLanguage.AF,
                    "Afrikaans",
                    "af"
                ),
                Language(
                    FirebaseTranslateLanguage.AR,
                    "Arabic",
                    "ar"
                ),
                Language(
                    FirebaseTranslateLanguage.BE,
                    "Belarusian",
                    "be"
                ),
                Language(
                    FirebaseTranslateLanguage.BG,
                    "Bulgarian",
                    "bg"
                ),
                Language(
                    FirebaseTranslateLanguage.BN,
                    "Bengali",
                    "bn"
                ),
                Language(
                    FirebaseTranslateLanguage.CA,
                    "Catalan",
                    "ca"
                ),
                Language(
                    FirebaseTranslateLanguage.CS,
                    "Czech",
                    "cs"
                ),
                Language(
                    FirebaseTranslateLanguage.CY,
                    "Welsh",
                    "cy"
                ),
                Language(
                    FirebaseTranslateLanguage.DA,
                    "Danish",
                    "da"
                ),
                Language(
                    FirebaseTranslateLanguage.DE,
                    "German",
                    "de"
                ),
                Language(
                    FirebaseTranslateLanguage.EL,
                    "Greek",
                    "el"
                ),
                Language(
                    FirebaseTranslateLanguage.EO,
                    "Esperanto",
                    "eo"
                ),
                Language(
                    FirebaseTranslateLanguage.ES,
                    "Spanish",
                    "es"
                ),
                Language(
                    FirebaseTranslateLanguage.ET,
                    "Estonian",
                    "et"
                ),
                Language(
                    FirebaseTranslateLanguage.FA,
                    "Persian",
                    "fa"
                ),
                Language(
                    FirebaseTranslateLanguage.FI,
                    "Finnish",
                    "fi"
                ),
                Language(
                    FirebaseTranslateLanguage.FR,
                    "French",
                    "fr"
                ),
                Language(
                    FirebaseTranslateLanguage.GA,
                    "Irish",
                    "ga"
                ),
                Language(
                    FirebaseTranslateLanguage.GL,
                    "Galician",
                    "gl"
                ),
                Language(
                    FirebaseTranslateLanguage.GU,
                    "Gujarati",
                    "gu"
                ),
                Language(
                    FirebaseTranslateLanguage.HE,
                    "Hebrew",
                    "he"
                ),
                Language(
                    FirebaseTranslateLanguage.HI,
                    "Hindi",
                    "hi"
                ),
                Language(
                    FirebaseTranslateLanguage.HR,
                    "Croatian",
                    "hr"
                ),
                Language(
                    FirebaseTranslateLanguage.HT,
                    "Haitian",
                    "ht"
                ),
                Language(
                    FirebaseTranslateLanguage.HU,
                    "Hungarian",
                    "hu"
                ),
                Language(
                    FirebaseTranslateLanguage.ID,
                    "Indonesian",
                    "id"
                ),
                Language(
                    FirebaseTranslateLanguage.IS,
                    "Icelandic",
                    "is"
                ),
                Language(
                    FirebaseTranslateLanguage.IT,
                    "Italian",
                    "it"
                ),
                Language(
                    FirebaseTranslateLanguage.JA,
                    "Japanese",
                    "ja"
                ),
                Language(
                    FirebaseTranslateLanguage.KA,
                    "Georgian",
                    "ka"
                ),
                Language(
                    FirebaseTranslateLanguage.KN,
                    "Kannada",
                    "kn"
                ),
                Language(
                    FirebaseTranslateLanguage.KO,
                    "Korean",
                    "ko"
                ),
                Language(
                    FirebaseTranslateLanguage.LT,
                    "Lithuanian",
                    "lt"
                ),
                Language(
                    FirebaseTranslateLanguage.LV,
                    "Latvian",
                    "lv"
                ),
                Language(
                    FirebaseTranslateLanguage.MK,
                    "Macedonian",
                    "mk"
                ),
                Language(
                    FirebaseTranslateLanguage.MR,
                    "Marathi",
                    "mr"
                ),
                Language(
                    FirebaseTranslateLanguage.MS,
                    "Malay",
                    "ms"
                ),
                Language(
                    FirebaseTranslateLanguage.MT,
                    "Maltese",
                    "mt"
                ),
                Language(
                    FirebaseTranslateLanguage.NO,
                    "Norwegian",
                    "no"
                ),
                Language(
                    FirebaseTranslateLanguage.PL,
                    "Polish",
                    "pl"
                ),
                Language(
                    FirebaseTranslateLanguage.PT,
                    "Portuguese",
                    "pt"
                ),
                Language(
                    FirebaseTranslateLanguage.RO,
                    "Romanian",
                    "ro"
                ),
                Language(
                    FirebaseTranslateLanguage.RU,
                    "Russian",
                    "ru"
                ),
                Language(
                    FirebaseTranslateLanguage.SK,
                    "Slovak",
                    "sk"
                ),
                Language(
                    FirebaseTranslateLanguage.SL,
                    "Slovenian",
                    "sl"
                ),
                Language(
                    FirebaseTranslateLanguage.SQ,
                    "Albanian",
                    "sq"
                ),
                Language(
                    FirebaseTranslateLanguage.SV,
                    "Swedish",
                    "sv"
                ),
                Language(
                    FirebaseTranslateLanguage.SW,
                    "Swahili",
                    "sw"
                ),
                Language(
                    FirebaseTranslateLanguage.TA,
                    "Tamil",
                    "ta"
                ),
                Language(
                    FirebaseTranslateLanguage.TE,
                    "Telugu",
                    "te"
                ),
                Language(
                    FirebaseTranslateLanguage.TH,
                    "Thai",
                    "th"
                ),
                Language(
                    FirebaseTranslateLanguage.TL,
                    "Tagalog",
                    "tl"
                ),
                Language(
                    FirebaseTranslateLanguage.TR,
                    "Turkish",
                    "tr"
                ),
                Language(
                    FirebaseTranslateLanguage.UK,
                    "Ukrainian",
                    "uk"
                ),
                Language(
                    FirebaseTranslateLanguage.UR,
                    "Urdu",
                    "ur"
                ),
                Language(
                    FirebaseTranslateLanguage.VI,
                    "Vietnamese",
                    "vi"
                ),
                Language(
                    FirebaseTranslateLanguage.ZH,
                    "Chinese",
                    "zh"
                )
            )
        }
    }
}